# Generated by Django 4.2 on 2023-05-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_name', models.CharField(max_length=200)),
                ('user_image', models.ImageField(blank=True, upload_to='blog_img/')),
            ],
        ),
    ]
