# Generated by Django 4.2 on 2023-05-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='phone',
            field=models.PositiveIntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
