# Generated by Django 4.2 on 2023-05-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_user_model_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='user_image',
            new_name='image',
        ),
    ]
