# Generated by Django 4.2 on 2023-05-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_rename_user_image_user_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='image',
        ),
    ]
