# Generated by Django 4.2 on 2023-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_user_model_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='username',
        ),
    ]
