# Generated by Django 4.2 on 2023-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_alter_post_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
