# Generated by Django 4.2 on 2023-05-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_post_model_user_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='user_con',
        ),
    ]
