# Generated by Django 4.2 on 2023-05-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_alter_post_model_user_con'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_model',
            old_name='user_con',
            new_name='user',
        ),
    ]
