# Generated by Django 4.2 on 2023-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_alter_post_model_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='post_model',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
